# Configuration for analysis parameters
# @package analysis

# Granularity for ternary analysis  
granularity: 0.1

# Downsampling options
downsampling:
  # Tree/locus-based downsampling (N=interval, i=starting_index)
  tree_interval: null  # e.g., 10 (every 10th tree)
  tree_start_index: 0
  
  # Position-based downsampling for chromosome mode (in kb)
  position_interval_kb: null  # e.g., 100 (every 100kb)
  position_start_kb: 0

# Topology mapping (optional)
# Format: 'T1=(0,(1,(2,3))); T2=(0,(2,(1,3))); T3=(0,(3,(1,2)));'
topology_mapping: null

# Fundamental asymmetry analysis settings
fundamental_asymmetry:
  filter_t2_equals_t3: true  # Filter out points where T2=T3