# Main configuration for TWISSTNTERN_SIMULATE

# Simulation template (integrated from config_template.yaml)
simulation:
  # Population labels
  population_labels:
    p1: "A"
    p2: "B" 
    p3: "C"
    p23: "Ancestor AB"
    p123: "Ancestor ABC"
    O: "Outgroup"
    ANC: "Ancestral"
  
  # Split times (in generations before present)
  splits:
    - time: 100
      derived_pop1: "p2"
      derived_pop2: "p3"
      ancestral_pop: "p23"
    - time: 200
      derived_pop1: "p23"
      derived_pop2: "p1"
      ancestral_pop: "p123"
    - time: 300
      derived_pop1: "p123"
      derived_pop2: "O"
      ancestral_pop: "ANC"
  
  # Effective population sizes
  populations:
    - name: "O"
      Ne: 1000
      sample_size: 10
    - name: "p1"
      Ne: 1000
      sample_size: 10
    - name: "p2"
      Ne: 1000
      sample_size: 10
    - name: "p3"
      Ne: 1000
      sample_size: 10
    - name: "p23"
      Ne: 1000
    - name: "p123"
      Ne: 1000
    - name: "ANC"
      Ne: 1000
  
  # Migration rates
  migration:
    "p1>p2": 0.01
    "p2>p1": 0.01
    "p1>p3": 0.000
    "p3>p1": 0.000
    "p2>p3": 0.000
    "p3>p2": 0.000
    "O>p1": 0.000
    "p1>O": 0.000
    "O>p2": 0.000
    "p2>O": 0.000
    "O>p3": 0.00
    "p3>O": 0.0000
    "p23>p1": 0.000
    "p1>p23": 0.00
    "O>p123": 0.0000
    "p123>O": 0.0000
  
  # Simulation mode
  simulation_mode: "locus"  # Choose: "locus", "chromosome"
  ploidy: 1  # Ploidy level: 1 for haploid, 2 for diploid
  seed: 4576  # Random seed for simulation
  
  # Locus mode parameters
  n_loci: 10000  # Number of loci/windows to simulate
  locus_length: 1  # Length of each locus in base pairs
  
  # Chromosome mode parameters  
  rec_rate: 1e-8  # Recombination rate per base per generation
  chromosome_length: 1e8  # Length of chromosome to simulate (in base pairs)
  mutation_rate: 0  # Mutation rate per base per generation

# Analysis configuration
config_file: null  # Path to external simulation config file (optional, overrides above)
output: "Results"  # Output directory
verbose: false  # Enable verbose output
quiet: false  # Suppress most output (only errors)
log_file: null  # Path to log file

# Simulation overrides
seed: null  # Random seed override (overrides simulation.seed)

# Analysis options
granularity: 0.1  # Granularity for ternary analysis
topology_mapping: null  # Custom topology mapping for T1/T2/T3

# Configuration overrides
override: []  # List of config value overrides in 'key=value' format

# Downsampling options
downsample: null  # Format: 'N' or 'N+i' where N=sample every Nth tree/locus
downsampleKB: null  # Format: 'Nkb' or 'Nkb+ikb' for kilobase-based sampling

# Visualization
density_colormap: "viridis"  # Colormap for density-colored ternary plot

# Hydra configuration for simulation mode
hydra:
  mode: RUN
  run:
    dir: .
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra:job.num}
  job:
    chdir: false  # Don't change working directory 